<?php
/** @var \Syedzaidi\FrontUi\Block\Frontui $block */

/** @var \Syedzaidi\FrontUi\ViewModel\PageList $viewModel */
$viewModel = $block->getData('viewModel');

?>
<h1><?= $block->getText(); ?></h1>

<div id="frontui" data-bind="scope: 'frontui'">
    <h1 data-bind="text: Data"></h1>
    <ul>
        <!-- ko foreach: { data: getItems(), as: 'page'} -->
        <li data-bind="text: page.title"></li>
        <p data-bind="text: page.url_key"></p>
        <!-- /ko -->
    </ul>
</div>

<script type="text/x-magento-init">
    {
        "#frontui": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "frontui": {
                        "component": "Syedzaidi_FrontUi/js/frontui",
                        "Data": "Data comes from viewModel Using UiComponent",
                        "items": <?= $viewModel->getItemsJson(); ?>
                    }
                }
            }
        }
    }
</script>